name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Docker CI Build
      run: |
        docker build -t docker.pkg.github.com/zealic/workshop-tonkotsu-nodejs/web:snapshot .
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run NPM Tests
      run: |
        npm install
        npm test
