name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Docker CI Build
      run: |
        env
        docker build -t zealic/hotpot:${{ github.head_ref }} .
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: zealic
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Docker hub
      run: |
        docker push zealic/hotpot:${{ github.head_ref	 }}
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run NPM Tests
      run: |
        npm install
        npm test
        npm run report-coverage
